# Generated by Django 2.1.4 on 2018-12-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huc',
            name='flow_allocation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='huc',
            name='initial_available_water',
            field=models.IntegerField(null=True),
        ),
    ]
