# Generated by Django 2.1.4 on 2018-12-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0003_auto_20181209_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpeciesComponents',
            new_name='SpeciesComponent',
        ),
    ]
