# Generated by Django 2.2.4 on 2019-09-06 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0004_auto_20181209_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_10', models.FloatField()),
                ('pct_25', models.FloatField()),
                ('pct_50', models.FloatField()),
                ('pct_75', models.FloatField()),
                ('pct_90', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StreamSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.CharField(max_length=25)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('downstream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='upstream_single_huc', to='belleflopt.StreamSegment')),
                ('upstream', models.ManyToManyField(related_name='all_downstream_segments', to='belleflopt.StreamSegment')),
            ],
        ),
        migrations.RemoveField(
            model_name='flowcomponent',
            name='species',
        ),
        migrations.AddField(
            model_name='flowcomponent',
            name='ceff_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SpeciesComponent',
        ),
        migrations.AddField(
            model_name='segmentcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='belleflopt.FlowComponent'),
        ),
        migrations.AddField(
            model_name='segmentcomponent',
            name='stream_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='belleflopt.StreamSegment'),
        ),
        migrations.AddField(
            model_name='flowcomponent',
            name='segments',
            field=models.ManyToManyField(related_name='components', through='belleflopt.SegmentComponent', to='belleflopt.StreamSegment'),
        ),
    ]
