# Generated by Django 2.2.4 on 2019-09-08 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0005_auto_20190905_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huc',
            name='flow_allocation',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='huc',
            name='initial_available_water',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='segmentcomponent',
            name='pct_10',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='segmentcomponent',
            name='pct_25',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='segmentcomponent',
            name='pct_50',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='segmentcomponent',
            name='pct_75',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='segmentcomponent',
            name='pct_90',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='SegmentPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.DecimalField(decimal_places=3, max_digits=4)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='belleflopt.Species')),
                ('stream_segment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='belleflopt.StreamSegment')),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='segments',
            field=models.ManyToManyField(related_name='species', through='belleflopt.SegmentPresence', to='belleflopt.StreamSegment'),
        ),
    ]
