# Generated by Django 2.2.4 on 2019-09-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0006_auto_20190908_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowcomponent',
            name='ceff_id',
        ),
        migrations.RemoveField(
            model_name='segmentcomponent',
            name='pct_10',
        ),
        migrations.RemoveField(
            model_name='segmentcomponent',
            name='pct_25',
        ),
        migrations.RemoveField(
            model_name='segmentcomponent',
            name='pct_50',
        ),
        migrations.RemoveField(
            model_name='segmentcomponent',
            name='pct_75',
        ),
        migrations.RemoveField(
            model_name='segmentcomponent',
            name='pct_90',
        ),
        migrations.AddField(
            model_name='segmentcomponent',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segmentcomponent',
            name='maximum_magnitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segmentcomponent',
            name='minimum_magnitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segmentcomponent',
            name='start_day',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowcomponent',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='SegmentComponentDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceff_code', models.CharField(max_length=30)),
                ('source_type', models.CharField(max_length=30, null=True)),
                ('source_name', models.CharField(max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pct_10', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pct_25', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pct_50', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pct_75', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pct_90', models.DecimalField(decimal_places=2, max_digits=8)),
                ('flow_component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='belleflopt.SegmentComponent')),
            ],
        ),
        migrations.CreateModel(
            name='FlowMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=100)),
                ('metric', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belleflopt.FlowComponent')),
            ],
        ),
    ]
