# Generated by Django 2.2.4 on 2019-09-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0007_auto_20190909_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamsegment',
            name='downstream_node_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamsegment',
            name='ftype',
            field=models.CharField(blank=True, choices=[('Connector', 'Connector'), ('CanalDitch', 'CanalDitch'), ('UndergroundConduit', 'UndergroundConduit'), ('PIPELINE', 'PIPELINE'), ('StreamRiver', 'StreamRiver'), ('ArtificialPath', 'ArtificialPath'), ('Coastline', 'Coastline')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='streamsegment',
            name='routed_upstream_area',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamsegment',
            name='strahler_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamsegment',
            name='subwatershed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='belleflopt.HUC'),
        ),
        migrations.AddField(
            model_name='streamsegment',
            name='total_upstream_area',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamsegment',
            name='upstream_node_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamsegment',
            name='com_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
