# Generated by Django 2.2.4 on 2019-09-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0008_auto_20190911_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamsegment',
            name='upstream',
            field=models.ManyToManyField(null=True, related_name='all_downstream_segments', to='belleflopt.StreamSegment'),
        ),
    ]
