# Generated by Django 2.2.4 on 2019-09-19 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0010_auto_20190911_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentcomponentdescriptor',
            name='ceff_code',
        ),
        migrations.AddField(
            model_name='segmentcomponentdescriptor',
            name='flow_metric',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='belleflopt.FlowMetric'),
            preserve_default=False,
        ),
    ]
