# Generated by Django 2.2.4 on 2019-09-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0013_auto_20190919_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcomponent',
            name='ceff_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
