# Generated by Django 2.2.4 on 2019-09-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0014_flowcomponent_ceff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmetric',
            name='metric',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='segmentcomponentdescriptor',
            name='flow_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='metrics', to='belleflopt.SegmentComponent'),
        ),
        migrations.AlterField(
            model_name='segmentcomponentdescriptor',
            name='flow_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descriptors', to='belleflopt.FlowMetric'),
        ),
        migrations.AlterUniqueTogether(
            name='segmentcomponent',
            unique_together={('stream_segment', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='segmentcomponentdescriptor',
            unique_together={('flow_component', 'flow_metric')},
        ),
    ]
