# Generated by Django 2.2.4 on 2019-09-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0015_auto_20190919_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentcomponent',
            name='duration_ramp',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='segmentcomponent',
            name='maximum_magnitude_ramp',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='segmentcomponent',
            name='minimum_magnitude_ramp',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='segmentcomponent',
            name='start_day_ramp',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
