# Generated by Django 2.2.4 on 2019-10-18 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0016_auto_20190920_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentcomponentdescriptor',
            name='flow_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descriptors', to='belleflopt.SegmentComponent'),
        ),
        migrations.AlterField(
            model_name='segmentcomponentdescriptor',
            name='pct_10',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='segmentcomponentdescriptor',
            name='pct_25',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='segmentcomponentdescriptor',
            name='pct_50',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='segmentcomponentdescriptor',
            name='pct_75',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='segmentcomponentdescriptor',
            name='pct_90',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
