# Generated by Django 2.2.4 on 2019-11-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0018_auto_20191114_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentcomponentdescriptor',
            name='associated_components_holding_dont_use',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
