# Generated by Django 2.2.4 on 2019-11-25 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0019_segmentcomponentdescriptor_associated_components_holding_dont_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_run', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='streamsegment',
            name='routed_upstream_area',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='streamsegment',
            name='total_upstream_area',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='FlowBenefitResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_iteration', models.IntegerField()),
                ('available_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('environmental_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('environmental_benefit', models.FloatField()),
                ('economic_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('economic_benefit', models.FloatField()),
                ('day_of_water_year', models.SmallIntegerField()),
                ('model_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belleflopt.ModelRun')),
            ],
        ),
    ]
