# Generated by Django 2.2.4 on 2019-11-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0020_auto_20191125_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentcomponent',
            name='duration_base',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='segmentcomponent',
            name='duration_ramp_base',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
