# Generated by Django 2.2.4 on 2020-01-25 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0021_auto_20191126_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_date', models.DateField()),
                ('water_year', models.SmallIntegerField()),
                ('water_year_day', models.SmallIntegerField()),
                ('estimated_flow', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stream_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belleflopt.StreamSegment')),
            ],
        ),
    ]
