# Generated by Django 2.2.4 on 2020-02-22 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0022_dailyflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyflow',
            old_name='estimated_flow',
            new_name='estimated_total_flow',
        ),
        migrations.AddField(
            model_name='dailyflow',
            name='estimated_upstream_flow',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyflow',
            name='model_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_flows', to='belleflopt.ModelRun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelrun',
            name='segments',
            field=models.ManyToManyField(to='belleflopt.StreamSegment'),
        ),
        migrations.AlterField(
            model_name='dailyflow',
            name='stream_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_flows', to='belleflopt.StreamSegment'),
        ),
    ]
