# Generated by Django 2.2.4 on 2020-02-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0024_auto_20200222_1526'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['pisces_fid'], name='belleflopt__pisces__deef91_idx'),
        ),
    ]
