# Generated by Django 2.2.4 on 2020-02-24 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0026_auto_20200222_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamsegment',
            name='species_presence',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='segmentpresence',
            name='stream_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='segment_presences', to='belleflopt.StreamSegment'),
        ),
        migrations.AlterField(
            model_name='streamsegment',
            name='downstream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='directly_upstream', to='belleflopt.StreamSegment'),
        ),
    ]
