# Generated by Django 2.2.4 on 2020-02-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0027_auto_20200224_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamsegment',
            name='species_presence',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
