# Generated by Django 2.2.4 on 2020-02-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0028_auto_20200224_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
