# Generated by Django 2.2.4 on 2020-02-29 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belleflopt', '0029_modelrun_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='water_year',
            field=models.SmallIntegerField(default=2010),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyflow',
            name='model_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_flows', to='belleflopt.ModelRun'),
        ),
        migrations.AlterUniqueTogether(
            name='segmentpresence',
            unique_together={('stream_segment', 'species')},
        ),
    ]
